### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Brainfodder**
Should allow game start with 1p/2p, pushed with the .zip via pandory.exe when tested.

### CODE REVIEW

**Comment by emuchicken** [comment]
Looking good.  
Can you add your name / credits in the cfg file (check youtube video)

**Comment by Brainfodder** [comment]
Hi Tim, do I need to pull again after doing that?

I adjusted them as soon as I saw that part of the video.

I went and looked still both active and didn't show any pull option, so if
one edits between pull request and it being seen, it's seen in the most
current state?

Regards,

Brian

**Comment by emuchicken** [comment]
Yes, like before- when you want your work to be published within pandory, you need to create a pull request.  I will close this request now, and then you can try again, ok?

**Comment by Brainfodder** [comment]
Hi, made it better and will be upgrading it and adding 2 more shortly, for
all 3, row 2 buttons 2 and 3 to start and coins, trying to use the actual
coin and combo play/coin are not working consistently on my end so this
change fixed it.

I'll be sure to pull at submit and I edited the cfg with my name in it
already....

Cheers!

**Comment by emuchicken** [comment]
Yeah, make sure you can tag in your name. 

And yes- Unsure if you're doing this currently-  check with the original arcade controls, so that your fixed controls replicate as closely as possible on a 6 button plate.

**Comment by Brainfodder** [comment]
I only have 6 button rigs so that IS what I stick to.  😁

**Pull request closed without merging**
